language: csharp
sudo: required
dist: trusty
notifications:
  email:
    on_success: change
    on_failure: change
script:
  - travis_retry ./build-package.sh
os:
  - linux
  - osx
env:
  global:
    - APM_TEST_PACKAGES='atom-yeoman linter json-schema advanced-open-file'
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
addons:
  apt:
    packages:
      - build-essential
      - git
      - libgnome-keyring-dev
      - fakeroot
      - libstdc++6
notifications:
  slack: omnisharp:UN1OlhsHD8hUXy8SEr1L6Zar
